export const ALL_COURSE_REQUEST = 'ALL_COURSE_REQUEST'
export const ALL_COURSE_SUCCESS = 'ALL_COURSE_SUCCESS'
export const ALL_COURSE_FAIL = 'ALL_COURSE_FAIL'


export const GET_COURSE = "GET_COURSE"
export const GET_COURSE_RED = "GET_COURSE_RED"


export const GET_COURSE_CATEGORY = "GET_COURSE_CATEGORY"
export const GET_COURSE_CATEGORY_RED = "GET_COURSE_CATEGORY_RED"

export const GET_CENTER = "GET_CENTER"
export const GET_CENTER_RED = "GET_CENTER_RED"

export const ADD_HOME_ENQUIRY = "ADD_HOME_ENQUIRY"
export const ADD_HOME_ENQUIRY_RED = "ADD_HOME_ENQUIRY_RED"


export const GET_UPCOMING_BATCHES = "GET_UPCOMING_BATCHES"
export const GET_UPCOMING_BATCHES_RED = "GET_UPCOMING_BATCHES_RED"

export const GET_SERVICE = "GET_SERVICE"
export const GET_SERVICE_RED = "GET_SERVICE_RED"

export const GET_CMS = "GET_CMS"
export const GET_CMS_RED = "GET_CMS_RED"

export const GET_DRIVE = "GET_DRIVE"
export const GET_DRIVE_RED = "GET_DRIVE_RED"

export const GET_TESTIMONIALS = "GET_TESTIMONIALS"
export const GET_TESTIMONIALS_RED = "GET_TESTIMONIALS_RED"

export const GET_PLACED_STUDENTS = "GET_PLACED_STUDENTS"
export const GET_PLACED_STUDENTS_RED = "GET_PLACED_STUDENTS_RED"

export const GET_COURSE_DROPDOWN_LIST = "GET_COURSE_DROPDOWN_LIST"
export const GET_COURSE_DROPDOWN_LIST_RED = "GET_COURSE_DROPDOWN_LIST_RED"


export const GET_GALLERY = "GET_GALLERY"
export const GET_GALLERY_RED = "GET_GALLERY_RED"

export const GET_CLIENTS = "GET_CLIENTS"
export const GET_CLIENTS_RED = "GET_CLIENTS_RED"


export const GET_BLOG_CATEGORY = "GET_BLOG_CATEGORY"
export const GET_BLOG_CATEGORY_RED = "GET_BLOG_CATEGORY_RED"

export const GET_BLOGS = "GET_BLOGS"
export const GET_BLOGS_RED = "GET_BLOGS_RED"
